### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by Heath123** [irmen/binaryen-interfaces#1]
```
Traceback (most recent call last):
  File "file.py", line 2, in <module>
    import binaryen
  File "/home/heath/.local/lib/python3.10/site-packages/binaryen.py", line 936, in <module>
    SwizzleVec8x16 = lib.BinaryenSwizzleVec8x16
AttributeError: cffi library '_binaryen' has no function, constant or global variable named 'BinaryenSwizzleVec8x16'
```

**Comment by Heath123** [comment]
This is with the version on PyPI which seems outdated

**Comment by Heath123** [comment]
It also seems to happen with the latest one though

**Comment by Heath123** [comment]
Commenting out that line seems to make it work

**Comment by irmen** [comment]
I updated it yesterday in 2af605a4bb3e6d29aa8d59742ebf5ec8df362413
You need binaryen release 108 .

I've not yet uploaded this to pypi but I will do so soon.

**Comment by irmen** [comment]
@Heath123 can you validate with the current master branch.

**Comment by irmen** [comment]
1.11 has been uploaded to pypi.

**Comment by Heath123** [comment]
Sorry, I think I had/have a slightly old Binaryen version installed with Emscripten (I didn't realise it used my system's installation)
